# Generated by Django 5.1.1 on 2024-09-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('capacite', models.IntegerField()),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Receveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.hopital')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.medecin')),
            ],
        ),
        migrations.CreateModel(
            name='Poche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tubulaire', models.CharField(max_length=50, unique=True)),
                ('groupe_sanguin', models.CharField(max_length=3)),
                ('quantite_ml', models.IntegerField()),
                ('date_de_collecte', models.DateField()),
                ('date_d_expiration', models.DateField()),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood.donateur')),
                ('receveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.receveur')),
            ],
        ),
    ]
