# Generated by Django 5.1.1 on 2024-09-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateur',
            old_name='groupe_sanguin',
            new_name='gs_rh',
        ),
        migrations.RenameField(
            model_name='poche',
            old_name='groupe_sanguin',
            new_name='gs_rh',
        ),
    ]
