# Generated by Django 5.1.1 on 2024-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_rename_groupe_sanguin_receveur_gs_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateur',
            name='bv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donateur',
            name='hcv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donateur',
            name='hiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donateur',
            name='hps',
            field=models.BooleanField(default=False),
        ),
    ]
